apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kube-multus-eni-attacher-ds
  namespace: kube-system
  labels:
    tier: node
    app: multus
    name: multus
spec:
  selector:
    matchLabels:
      name: multus
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        tier: node
        app: multus
        name: multus
    spec:
      hostNetwork: true
      tolerations:
      - operator: Exists
        effect: NoSchedule
      serviceAccountName: multus
      containers:
      - name: kube-multus
        image: <your repo>/eks-multus-daemonset:latest
        command: ["/sbin/entrypoint.sh"]
        securityContext:
          privileged: true
      terminationGracePeriodSeconds: 10